spring:
  datasource:
    url: ENC(8oc0zJcM+7qNTzKRyqbwdpf5DW1b8SIYway8+NLWMfIaPEqpD4AwlB9TCGP7iy4k30qzcXjRK/DX5HcT1wSXtSZFavXMCBNkIys2swD1i0w6tt8VBncHQm7UypW0IhI9rQJgCsSOnWg=)
    username: ENC(vtRKhpTKNF0EiMt2SxPA4A==)
    password: ENC(zYl8pMvttdzEyZ0YN1jMfQy0eLw8lhGB)
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 30
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 60000


