spring:
  datasource:
    url: jdbc:mysql://121.40.212.118/astrovis?useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: jcy
    password: XPVis1234!
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      validation-query: SELECT 1
      test-while-idle: true
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 60000


