package com.astrovis.astrovisbackend.model;

import java.util.Date;

public class UploadedFile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.fileId
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    private String fileid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.fileName
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    private String filename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.uploader
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    private Integer uploader;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.fileStatus
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    private Integer filestatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.category
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    private Integer category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.lastAccessed
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    private Date lastaccessed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.originalFileName
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    private String originalfilename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.parameters
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    private String parameters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_uploaded_file.deleted
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    private Boolean deleted;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.fileId
     *
     * @return the value of t_uploaded_file.fileId
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public String getFileid() {
        return fileid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.fileId
     *
     * @param fileid the value for t_uploaded_file.fileId
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public void setFileid(String fileid) {
        this.fileid = fileid == null ? null : fileid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.fileName
     *
     * @return the value of t_uploaded_file.fileName
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.fileName
     *
     * @param filename the value for t_uploaded_file.fileName
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.uploader
     *
     * @return the value of t_uploaded_file.uploader
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public Integer getUploader() {
        return uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.uploader
     *
     * @param uploader the value for t_uploaded_file.uploader
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public void setUploader(Integer uploader) {
        this.uploader = uploader;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.fileStatus
     *
     * @return the value of t_uploaded_file.fileStatus
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public Integer getFilestatus() {
        return filestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.fileStatus
     *
     * @param filestatus the value for t_uploaded_file.fileStatus
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public void setFilestatus(Integer filestatus) {
        this.filestatus = filestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.category
     *
     * @return the value of t_uploaded_file.category
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public Integer getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.category
     *
     * @param category the value for t_uploaded_file.category
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public void setCategory(Integer category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.lastAccessed
     *
     * @return the value of t_uploaded_file.lastAccessed
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public Date getLastaccessed() {
        return lastaccessed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.lastAccessed
     *
     * @param lastaccessed the value for t_uploaded_file.lastAccessed
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public void setLastaccessed(Date lastaccessed) {
        this.lastaccessed = lastaccessed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.originalFileName
     *
     * @return the value of t_uploaded_file.originalFileName
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public String getOriginalfilename() {
        return originalfilename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.originalFileName
     *
     * @param originalfilename the value for t_uploaded_file.originalFileName
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public void setOriginalfilename(String originalfilename) {
        this.originalfilename = originalfilename == null ? null : originalfilename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.parameters
     *
     * @return the value of t_uploaded_file.parameters
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public String getParameters() {
        return parameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.parameters
     *
     * @param parameters the value for t_uploaded_file.parameters
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public void setParameters(String parameters) {
        this.parameters = parameters == null ? null : parameters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_uploaded_file.deleted
     *
     * @return the value of t_uploaded_file.deleted
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_uploaded_file.deleted
     *
     * @param deleted the value for t_uploaded_file.deleted
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}