package com.astrovis.astrovisbackend.mappers;

import com.astrovis.astrovisbackend.model.UploadedFile;
import com.astrovis.astrovisbackend.model.UploadedFileExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UploadedFileMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uploaded_file
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    long countByExample(UploadedFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uploaded_file
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    int deleteByExample(UploadedFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uploaded_file
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    int insert(UploadedFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uploaded_file
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    int insertSelective(UploadedFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uploaded_file
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    List<UploadedFile> selectByExample(UploadedFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uploaded_file
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    int updateByExampleSelective(@Param("row") UploadedFile row, @Param("example") UploadedFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_uploaded_file
     *
     * @mbg.generated Sun Feb 02 19:18:11 EST 2025
     */
    int updateByExample(@Param("row") UploadedFile row, @Param("example") UploadedFileExample example);
}